package list

var Categories = map[string]string{
	"Development":                      "👨‍💻",
	"Government":                       "🏛️",
	"Transportation":                   "🚇",
	"Entertainment":                    "🍿",
	"Travel":                           "✈️",
	"Finance & Economics":              "🏦",
	"Payments":                         "💳",
	"Commerce":                         "💰",
	"Health":                           "💊",
	"Games":                            "🎮",
	"Sport & Fitness":                  "⚾",
	"Vehicles":                         "🚗",
	"AI & ML":                          "🤖",
	"Adult":                            "🍓",
	"Analytics":                        "📈",
	"Animals":                          "🐈",
	"Art & Design":                     "🎨",
	"Authentication & User Management": "👥",
	"Bar & QR Codes":                   "🏪",
	"Blockchain & Cryptocurrencies":    "📒️",
	"Bookmarks":                        "📑",
	"Books":                            "📚",
	"Bots":                             "📝",
	"Business":                         "👔",
	"CRM":                              "🤝",
	"Calendar & Time":                  "📅",
	"Casino & Gambling":                "🎰",
	"Chats & Messaging":                "💬",
	"Collaboration":                    "👨‍👩‍👦‍👦",
	"Education":                        "🎓",
	"Email & SMS":                      "📨",
	"Fun":                              "🤪",
	"Food & Drinks":                    "🍹",
	"Images & Photography":             "📸",
	"News & Feeds":                     "📰",
	"Search":                           "🔎",
	"Security":                         "🛡️",
	"Weather":                          "☔",
	"Space":                            "🚀",
	"Video & Media":                    "🎥",
	"Maps & Geo":                       "📌",
	"Documents & Productivity":         "📋",
	"Files & Storage":                  "💾",
	"Environment & Nature":             "🌲",
	"Post & Logistics":                 "📬",
	"Science & Math":                   "🔬",
	"Events":                           "🏟️",
	"Voice":                            "🎙️",
	"Random":                           "🎲",
	"IoT & Home Automation":            "🏠",
	"URLs":                             "🔗",
	"Music & Audio":                    "🎸",
	"Text Analysis & Tools":            "📖",
	"Statistics & Data":                "\U0001F9EE",
	"Visualizations":                   "📊",
	"Translation":                      "㊗️",
	"Validation & Verification":        "✅",
	"Marketing & SEO":                  "💰",
	"Project Management":               "🚧",
	"Jobs":                             "🛠️",
	"Databases":                        "🗄️",
	"Comics & Anime":                   "\U0001F9B8🏻‍️️",
	"Testing":                          "🐞",
	"Hardware":                         "⚙️",
	"Virtual & Augmented Reality":      "📱",
	"Other":                            "✨",
	"Point of Interest":                "🍺",
	"Open Source":                      "🔓",
	"Real Estate":                      "🏗️",
	"Recognition":                      "🔬",
	"Scrapers & Data Mining":           "🕸️",
	"Content & Dictionaries":           "",
	"Social":                           "",
	"Forms & Surveys":                  "",
	"Wiki":                             "",
	"Captcha":                          "",
}
