package builder

var CategoryIcons = map[string]string{
	"Development":                      "👨‍💻",
	"Government":                       "🏛️",
	"Transportation":                   "🚇",
	"Entertainment":                    "🍿",
	"Travel":                           "✈️",
	"Finance & Economics":              "🏦",
	"Payments":                         "💳",
	"Commerce":                         "💰",
	"Health":                           "💊",
	"Games":                            "🎮",
	"Sport & Fitness":                  "⚾",
	"Vehicle & Transportation":         "🚗",
	"AI & ML":                          "",
	"Adult":                            "",
	"Analytics":                        "📈",
	"Animals":                          "🐈",
	"Art & Design":                     "",
	"Authentication & User Management": "",
	"Automation":                       "",
	"Bar & QR Codes":                   "",
	"Blockchain & Cryptocurrencies":    "",
	"Bookmarks":                        "",
	"Books":                            "📚",
	"Bots":                             "",
	"Business":                         "",
	"CRM":                              "",
	"Calendar & Time":                  "",
	"Captcha":                          "",
	"Casino & Gambling":                "🎰",
	"Chats & Messaging":                "",
	"Collaboration":                    "",
	"Comics & Anime":                   "",
	"Communications":                   "",
	"Content & Dictionaries":           "",
	"Databases":                        "",
	"Documents & Productivity":         "",
	"Education":                        "🎓",
	"Email & SMS":                      "📨",
	"Environment & Nature":             "",
	"Events":                           "",
	"Files & Storage":                  "",
	"Food & Drinks":                    "🍹",
	"Forms & Surveys":                  "",
	"Fun":                              "🤪",
	"Hardware":                         "",
	"Images & Photography":             "",
	"IoT & Home Automation":            "",
	"Jobs":                             "",
	"Maps & Geo":                       "",
	"Marketing & SEO":                  "",
	"Music & Audio":                    "",
	"News & Feeds":                     "",
	"Open Source":                      "",
	"Other":                            "",
	"Point of Interest":                "",
	"Post & Logistics":                 "",
	"Products":                         "",
	"Project Management":               "",
	"Random":                           "",
	"Real Estate":                      "",
	"Recognition":                      "",
	"Science & Math":                   "",
	"Scrapers & Data Mining":           "",
	"Search":                           "",
	"Security":                         "",
	"Social":                           "",
	"Space":                            "",
	"Statistics & Data":                "",
	"Testing":                          "",
	"Text":                             "",
	"Text Analysis":                    "",
	"Tools":                            "",
	"Translation":                      "",
	"Trivia":                           "",
	"URL Shortening":                   "",
	"URLs":                             "",
	"Validation & Verification":        "",
	"Video & Media":                    "",
	"Virtual & Augmented Reality":      "",
	"Visualizations":                   "",
	"Voice":                            "",
	"Weather":                          "☔",
	"Wiki":                             "",
	"Worldwide":                        "🗺️",
}
