const Categories = [
    {
        name: "AI & ML",
        icon: "🤖",
        aliases: ["Predictions", "Auto Categorization", "AI", "Machine Learning"]
    },
]


/*
"Analytics": {"Analytics", "Statistics"},
	"Animals": {"Animals", "Pets", "Dogs"},
	"Comics & Anime": {"Anime & Comics", "Anime", "Comics"},
	"Applications": {"Applications"},
	"Art & Design": {"Art & Design", "Art", "Design"},
	"Authentication": {"Authentication", "Autorization"},
	"Big Data": {"Big Data"},
	"Blockchain & Cryptocurrencies": {"Blockchain / Cryptocurrencies", "Bitcoin", "Dlt"},
	"Blogging": {"Blogging"},
	"Bookmarks": {"Bookmarks"},
	"Books": {"Books"},
	"Bots": {"Bots"},
	"Business": {"Business", "Sales"},
	"Calendar": {"Calendar"},
	"Captcha": {"Captcha"},
	"Casino & Gambling": {"Casino & Gambling"},
	"Chats & Messaging": {"Chats & Messaging", "Chat", "Messaging"},
	"Cloud": {"Cloud"},
	"Communications": {"Telephony"},
	"Collaboration": {"Collaboration"},
	"Commerce & Marketplaces": {"Commerce", "Marketplace", "Prices", "Retail", "Pim", "ECommerce", "Discounts"},
	"Content & Dictionaries": {"Content & Dictionaries", "Dictionaries", "Dictionary"},
	"Conversions": {"Conversions"},
	"Countries": {"Countries", "African", "Russian", "USA"},
	"Currency": {"Currency"},
	"Customer Relationship Management": {"Customer Relationship Management"},
	"Databases": {"Database-As-A-Service", "Databases", "Database"},
	"Development": {"Development", "Resources For Design And Discovery Of APIs", "Backend", "Developers", "Application Development"},
	"Documents & Productivity": {"Documents & Productivity", "Spreadsheets", "PDF", "Work", "Document Collection", "Time Tracking:"},
	"Education": {"Education"},
	"Email & SMS": {"Email & SMS", "Email Api", "Transactional Email Api", "Email"},
	"Entertainment": {"Entertainment", "Tv"},
	"Environment": {"Environment"},
	"Events": {"Events"},
	"Files & Storage": {"Files & Storage", "Storage", "Upload", "File Storage", "File Sharing", "File Analysis"},
	"Finance & Economics": {"Finance", "Economics", "Stocks"},
	"Food & Drinks": {"Food & Drinks", "Food & Drink", "Nutrition", "Recipes"},
	"Forms": {"Forms"},
	"Games & Comics": {"Games & Comics", "Videogames", "Games"},
	"Government": {"Government", "Central Banks"},
	"Health": {"Health"},
	"Humor": {"Humor"},
	"Images": {"Images", "Images & Media"},
	"Invoicing": {"Invoicing"},
	"IoT & Home Automation": {"IoT & Home Automation", "IoT"},
	"Jobs": {"Jobs"},
	"Language": {"Language"},
	"Localization": {"Localization"},
	"Logistics": {"Logistics"},
	"Maps & Geo": {"Maps & Geo", "Viewer"},
	"Marine": {"Marine"},
	"Marketing": {"Marketing", "Video Marketing"},
	"Math & Science": {"Math & Science"},
	"Measurements": {"Measurements"},
	"Mobile": {"Mobile"},
	"Monitoring": {"Monitoring"},
	"Movies": {"Movies"},
	"Museums": {"Museums"},
	"Music & Audio": {"Music", "Music Stores", "Audio"},
	"Natural Language Processing": {"Natural Language Processing"},
	"News & Feeds": {"News & Feeds", "News", "News Services"},
	"Non-Profit": {"Non-Profit"},
	"Notepads": {"Notepads"},
	"Notifications": {"Notifications"},
	"Office": {"Office"},
	"Open Data": {"Open Data", "Data"},
	"Open Licenses": {"Open Licenses"},
	"Open Source": {"Open Source", "Open Source Projects"},
	"Optimization": {"Optimization"},
	"Other": {"Other", "Solar Data"},
	"Patent": {"Patent"},
	"Payments": {"Payments", "Billing", "Transactions"},
	"Personality": {"Personality"},
	"Photography": {"Photos", "Photography"},
	"Platform-As-A-Service": {"Platform-As-A-Service"},
	"Podcasts": {"Podcasts"},
	"Politics": {"Politics"},
	"Postal": {"Postal", "Zip Codes", "Postcodes", "Zip Code Api"},
	"Products": {"Products"},
	"Profiles": {"Profiles"},
	"Project Management": {"Project Management"},
	"Publishing": {"Publishing"},
	"Q&A": {"Q&A"},
	"Bar & QR Codes": {"Bar & QR Codes", "QR Codes", "BarCode"},
	"Quotes": {"Quotes"},
	"Random": {"Random"},
	"Ratings": {"Ratings"},
	"Real Estate": {"Real Estate"},
	"Real Time": {"Real Time"},
	"Recognition": {"Recognition"},
	"Recreation": {"Recreation"},
	"Reference": {"Reference"},
	"Referrals": {"Referrals"},
	"Religion": {"Religion"},
	"Reporting": {"Reporting"},
	"Restaurants": {"Restaurants"},
	"Rewards": {"Rewards"},
	"Routing": {"Routing"},
	"SDK": {"SDK"},
	"SEO": {"SEO"},
	"Safety": {"Safety"},
	"Scheduling": {"Scheduling"},
	"Science & Math": {"Science & Math", "Science"},
	"Scrapers & Data Mining": {"Scrapers & Data Mining", "Recipe Html Scrape To Json"},
	"Screenshots": {"Screenshots"},
	"Search": {"Search"},
	"Security": {"Security"},
	"Shipping": {"Shipping"},
	"Shopping": {"Shopping"},
	"Skills": {"Skills"},
	"Social": {"Social", "Networking"},
	"Software-As-A-Service": {"Software-As-A-Service"},
	"Space": {"Space"},
	"Spam": {"Spam"},
	"Spelling": {"Spelling"},
	"Sport & Fitness": {"Sport & Fitness", "Sports & Fitness", "Football", "Soccer"},
	"Static Analysis": {"Static Analysis"},
	"Subscriptions": {"Subscriptions"},
	"Surveys": {"Surveys"},
	"Sustainability": {"Sustainability"},
	"TV": {"TV"},
	"Tagging": {"Tagging"},
	"Tasks": {"Tasks"},
	"Taxes": {"Taxes"},
	"Testing": {"Testing", "Test Data"},
	"Text": {"Text"},
	"Text Analysis": {"Text Analysis", "Semantics", "Sentiment", "Word Processing", "Text Summarization", "Summary"},
	"Tickets": {"Tickets"},
	"Time": {"Time"},
	"Time Tracking": {"Time Tracking"},
	"Tools": {"Tools"},
	"Tracking": {"Tracking"},
	"Translation": {"Translation"},
	"Transportation": {"Transportation"},
	"Travel": {"Travel", "Travel, Webcams", "Tourism"},
	"Trivia": {"Trivia"},
	"URL Shortening": {"URL Shortening", "Url Shortener", "Url Shorteners", "Url Shortening", "URL Shortener", "URL Shorteners"},
	"URLs": {"URLs", "Urls"},
	"Validation & Verification": {"Validation & Verification", "Validation", "Verification", "Validation Api", "Email Validation"},
	"Vehicle": {"Vehicle", "Auto"},
	"Video & Media": {"Video & Media", "Streaming", "Transcoding", "Video", "Video Experiences", "Youtube"},
	"Virtual Reality": {"Virtual Reality"},
	"Visual Content Recognition": {"Visual Content Recognition"},
	"Visualizations": {"Visualizations"},
	"Voice": {"Voice", "Text To Speech", "Text-To-Speech", "Voip"},
	"Water": {"Water"},
	"Wearable": {"Wearable"},
	"Weather": {"Weather"},
	"Web": {"Web"},
	"Web Site Management": {"Web Site Management"},
	"Webhooks": {"Webhooks"},
	"Writing": {"Writing"},
 */
